# Generated by Django 3.0.6 on 2020-05-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='rollNo',
            new_name='rollno',
        ),
    ]
