# Generated by Django 3.0.6 on 2020-05-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20200527_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phonenumber',
        ),
    ]
